#!/usr/bin/env python3
"""
The one place that decides where generated data lives and how the site loads it.

Each generator writes its result as a per-batch JSON file in data/:

    data/roster-2027.json      from generate_roster_data.py
    data/weekly-2027.json      from generate_weekly_data.py
    data/roster-test.json      the TEST roll, hand-edited

and then calls bundle() here, which rebuilds the two files the pages load:

    js/roster-data.js               every data/roster-*.json merged
    weekly-seat/js/weekly-data.js   every data/weekly-*.json, keyed by batch

So the HTML pages never change when a batch is added, and updating one batch
can't touch another's data: its JSON file is the only thing rewritten.

Run this file directly to rebuild the bundles after hand-editing a JSON file:

    python scripts/site_data.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
ROSTER_JS = ROOT / "js" / "roster-data.js"
WEEKLY_JS = ROOT / "weekly-seat" / "js" / "weekly-data.js"
HEADER = "// Generated by scripts/site_data.py from data/%s-*.json. Do not hand-edit.\n"


def _dump(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def load_catalog(batch):
    path = DATA / ("batch-%s.json" % batch)
    if not path.exists():
        sys.exit("No catalog for batch %s: expected %s" % (batch, path))
    return json.loads(path.read_text(encoding="utf-8"))


def detect_batch(text):
    """Pick the batch whose years (e.g. "2025-27") appear in a schedule's text."""
    found = []
    for path in sorted(DATA.glob("batch-*.json")):
        catalog = json.loads(path.read_text(encoding="utf-8"))
        m = re.search(r"(20\d{2})\s*-\s*(\d{2})", catalog.get("label", ""))
        if m and re.search(r"%s\s*-\s*%s" % (m.group(1), m.group(2)), text):
            found.append(catalog["batch"])
    if len(found) != 1:
        sys.exit("Could not tell which batch this file is for (matched: %s). "
                 "Pass the batch explicitly, e.g. 2027." % (found or "none"))
    return found[0]


def save(kind, batch, obj):
    """Write one batch's generated data, then rebuild what the site loads."""
    path = DATA / ("%s-%s.json" % (kind, batch))
    path.write_text(_dump(obj) + "\n", encoding="utf-8")
    print("Wrote %s" % path)
    bundle()


def bundle():
    roster, owner = {}, {}
    for path in sorted(DATA.glob("roster-*.json")):
        for roll, entry in json.loads(path.read_text(encoding="utf-8")).items():
            if roll in roster:
                sys.exit("Roll %s is in both %s and %s. Nothing bundled." % (roll, owner[roll], path.name))
            roster[roll], owner[roll] = entry, path.name
    ROSTER_JS.write_text((HEADER % "roster") + "window.ROSTER_DATA = %s;\n" % _dump(roster), encoding="utf-8")

    weekly = {}
    for path in sorted(DATA.glob("weekly-*.json")):
        week = json.loads(path.read_text(encoding="utf-8"))
        weekly[week["batch"]] = week
    WEEKLY_JS.write_text((HEADER % "weekly") + "window.WEEKLY_DATA = %s;\n" % _dump(weekly), encoding="utf-8")

    print("Site data rebuilt: %d students in the roster; weekly schedules for %s"
          % (len(roster), ", ".join("batch %s (week of %s)" % (b, w["week"]["start"]) for b, w in sorted(weekly.items())) or "no batch"))


if __name__ == "__main__":
    bundle()
