#!/usr/bin/env python3
"""
The one command that keeps the site's data current:

    python scripts/update.py

What it does, every time:

 1. Files anything waiting in "all files/_inbox/". Each file is read to find
    out what it is (weekly schedule, course allocation or student list) and
    which batch, programme group and term it belongs to, then moved to
        all files/batch <year>/<core|bfs|dcp>/term <n>/[weekly/]
    under its original name. A file it cannot place is left in the inbox and
    reported.
 2. Reads every file under "all files/" again from scratch and rebuilds the
    master data in data/master/:
        students.json   every student: programme, batch, section, courses
        courses.json    course lists per batch, group and term
        weekly/         every week ever received, per batch and group
 3. Rebuilds the three files the pages load:
        js/site-data.js                 programmes and term timeline
        js/roster-data.js               every student, compact
        weekly-seat/js/weekly-data.js   the two newest weeks per group

Because step 2 always starts from the college's own files, the master data
can never drift from them, and adding a batch, a programme or a term is just
adding files in the right folder.

A file that fails its checks is skipped with a message and everything else
still builds; the previous data for that one schedule is simply not there.
Hand-edited settings live in data/config/ (programmes, timeline, overrides).

    pip install pymupdf xlrd openpyxl      # once
"""
import datetime as dt
import json
import re
import shutil
import sys
from pathlib import Path

import parsers

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "all files"
INBOX = SOURCE / "_inbox"
CONFIG = ROOT / "data" / "config"
MASTER = ROOT / "data" / "master"
WEEKS_ON_SITE = 2
FOLDER = re.compile(r"batch (\d{4})/(core|bfs|dcp)/term (\d)(/|$)")

messages = []


def say(kind, text):
    messages.append((kind, text))
    print("%-8s %s" % (kind, text))


def load(name):
    return json.loads((CONFIG / name).read_text(encoding="utf-8"))


def dump(obj, **kw):
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, **kw)


def write_json(path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dump(obj, indent=1) + "\n", encoding="utf-8")


def write_js(path, comment, name, obj):
    path.write_text("// Generated by scripts/update.py. Do not hand-edit. %s\nwindow.%s = %s;\n"
                    % (comment, name, dump(obj, separators=(",", ":"))), encoding="utf-8")


# ------------------------------------------------------------------ 1. inbox

def file_inbox(timeline):
    INBOX.mkdir(parents=True, exist_ok=True)
    today = dt.date.today().isoformat()
    for path in sorted(p for p in INBOX.iterdir() if p.is_file()):
        try:
            info = parsers.describe(path)
        except Exception as e:  # unreadable file: leave it where it is
            say("INBOX", "left in inbox, could not be read: %s (%s)" % (path.name, e))
            continue
        if info.get("_code"):
            info["group"] = programmes["programmes"].get(info["_code"], {}).get("group", info["group"])
        if info["kind"] == "weekly" and not info["batch"] and info["group"] and info["term"]:
            # no "2026-28" anywhere in it: the batch is whichever one has this
            # group in this term during the schedule's week
            try:
                start = parsers.parse_weekly(path)["start"]
                hits = [k.split("-")[0] for k, v in timeline.items()
                        if k.endswith("-" + info["group"]) and current_term(v, start) == info["term"]]
                if len(hits) == 1:
                    info["batch"] = hits[0]
            except Exception:
                pass
        if info["term"] is None and info["batch"] and info["group"]:
            info["term"] = current_term(timeline.get("%s-%s" % (info["batch"], info["group"])), today)
        if not all(info.get(k) for k in ("kind", "batch", "group", "term")):
            say("INBOX", "left in inbox, could not tell what it is: %s (read as %s)"
                % (path.name, {k: v for k, v in info.items() if not k.startswith("_")}))
            continue
        dest = SOURCE / ("batch %s" % info["batch"]) / info["group"] / ("term %d" % info["term"])
        if info["kind"] == "weekly":
            dest = dest / "weekly"
        dest.mkdir(parents=True, exist_ok=True)
        if (dest / path.name).exists():
            say("INBOX", "replaced the earlier copy of %s" % path.name)
        shutil.move(str(path), str(dest / path.name))
        say("FILED", "%s -> %s" % (path.name, dest.relative_to(SOURCE).as_posix()))


def current_term(group_timeline, today):
    term = None
    for t in (group_timeline or {}).get("terms", []):
        if t["start"] <= today or term is None:
            term = t["term"]
    return term


# ------------------------------------------------------------------ 2. master

def build_master(overrides):
    found = {}  # (batch, group, term) -> {'weekly': [paths], 'other': [paths]}
    for path in sorted(SOURCE.rglob("*")):
        rel = path.relative_to(SOURCE).as_posix()
        m = FOLDER.match(rel)
        if not path.is_file() or not m:
            continue
        key = (m.group(1), m.group(2), int(m.group(3)))
        bucket = "weekly" if "/weekly/" in rel else "other"
        found.setdefault(key, {"weekly": [], "other": []})[bucket].append(path)

    courses, students, weeks = {}, {}, {}
    latest_term = {}
    for (batch, group, term) in sorted(found):
        latest_term[(batch, group)] = max(term, latest_term.get((batch, group), 0))

    for (batch, group, term), files in sorted(found.items()):
        key = "%s-%s-%d" % (batch, group, term)
        gkey = "%s-%s" % (batch, group)
        catalog = {}
        lists = []
        for path in files["other"]:
            try:
                kind = parsers.describe(path)["kind"]
                if kind == "courses":
                    parsed, warns = parsers.parse_courses(path)
                    catalog.update(parsed)
                    for w in warns:
                        say("NOTE", w)
                elif kind == "students":
                    lists.append(path)
                else:
                    say("SKIPPED", "%s: not a course or student list" % path.relative_to(SOURCE).as_posix())
            except Exception as e:
                say("SKIPPED", "%s: %s" % (path.relative_to(SOURCE).as_posix(), e))
        for abb, name in overrides["courses"].get(key, {}).items():
            catalog.setdefault(abb, {})["name"] = name
        courses[key] = catalog

        # the newest term's lists describe where each student is now
        if term == latest_term[(batch, group)]:
            for path in lists:
                try:
                    parsed, notes = parsers.parse_students(path, catalog)
                    for n in notes:
                        say("NOTE", n)
                except Exception as e:
                    say("SKIPPED", "%s: %s" % (path.relative_to(SOURCE).as_posix(), e))
                    continue
                for roll, entry in parsed.items():
                    if roll in students and students[roll]["group"] != group:
                        say("NOTE", "roll %s is in both the %s and %s lists" % (roll, students[roll]["group"], group))
                    code = roll[2:6] if re.fullmatch(r"\d{9}", roll) else ("FPM" if "FPM" in roll else None)
                    entry.update(batch=batch, group=group, term=term, programme=code)
                    if entry.get("electives") and students.get(roll, {}).get("electives"):
                        both = sorted(set(students[roll]["electives"]) | set(entry["electives"]))
                        if len(both) > 1:
                            say("NOTE", "roll %s is on more than one elective list (%s); shown all of them" % (roll, ", ".join(both)))
                        entry["electives"] = both
                    students[roll] = {**students.get(roll, {}), **entry}

        for path in files["weekly"]:
            rel = path.relative_to(SOURCE).as_posix()
            try:
                week = parsers.parse_weekly(path)
            except Exception as e:
                say("SKIPPED", "%s: %s" % (rel, e))
                continue
            if week["term"] not in (None, term):
                say("NOTE", "%s says Term %s but sits in the term %d folder" % (rel, week["term"], term))
            week.update(batch=batch, group=group, term=term, source=rel)
            lookup = {parsers.norm_code(a): a for a in catalog}
            names = {}
            for s in week["sessions"]:
                abb = lookup.get(parsers.norm_code(s["c"]))
                if abb:
                    names[s["c"]] = catalog[abb]["name"]
                else:
                    names[s["c"]] = s["c"]
            unknown = sorted(c for c, n in names.items() if c == n)
            if unknown:
                week["warnings"].append("no course name for %s (add to data/config/overrides.json)" % ", ".join(unknown))
            week["courses"] = names
            week["electives"] = overrides["electives"].get(key, [])
            for w in week.pop("warnings"):
                say("NOTE", "%s: %s" % (gkey, w))
            weeks.setdefault(gkey, {})[week["start"]] = week
            say("WEEK", "%s term %d, %s to %s: %d classes, %d other entries  [%s layout]"
                % (gkey, term, week["start"], week["end"], len(week["sessions"]), len(week["specials"]), week["mode"]))

    for roll, entry in overrides["students"].items():
        if roll.startswith("_"):
            continue
        students[roll] = {**students.get(roll, {}), **entry}

    # stop-gap sections: only for students whose lists give no section
    assumed = {}
    for s in students.values():
        rule = overrides["sectionFromElective"].get("%s-%s-%s" % (s["batch"], s["group"], s.get("term")))
        chosen = [e for e in s.get("electives", []) if rule and e in rule]
        if rule and not s.get("section") and len(chosen) == 1:
            s["section"] = rule[chosen[0]]
            s["sectionAssumed"] = True
            key = "%s-%s" % (s["batch"], s["group"])
            assumed[key] = assumed.get(key, 0) + 1
    for key, n in sorted(assumed.items()):
        say("NOTE", "%s: %d students given a section from their elective (stop-gap in overrides.json)" % (key, n))
    return courses, students, weeks


# ------------------------------------------------------------------- 3. site

def build_site(courses, students, weeks, timeline):
    shutil.rmtree(MASTER, ignore_errors=True)
    write_json(MASTER / "students.json", students)
    write_json(MASTER / "courses.json", courses)
    for gkey, by_start in weeks.items():
        for start, week in by_start.items():
            write_json(MASTER / "weekly" / gkey / ("%s.json" % start), week)

    roster = {}
    short = {"name": "n", "section": "s", "major": "mj", "minor": "mn", "track": "t",
             "courses": "c", "electives": "e", "programme": "p", "alumni": "al"}
    for roll, s in students.items():
        entry = {"g": "%s-%s" % (s["batch"], s["group"])}
        for long, key in short.items():
            if s.get(long):
                entry[key] = s[long]
        roster[roll] = entry
    write_js(ROOT / "js" / "roster-data.js", "Every student in data/master/students.json.", "ROSTER_DATA", roster)

    site_weeks = {}
    for gkey, by_start in weeks.items():
        newest = [by_start[k] for k in sorted(by_start)[-WEEKS_ON_SITE:]]
        site_weeks[gkey] = [{k: w[k] for k in ("term", "weekNumber", "start", "end", "mode", "rowLabel", "rows",
                                               "slots", "days", "sessions", "specials", "courses", "electives")}
                            for w in newest]
    write_js(ROOT / "weekly-seat" / "js" / "weekly-data.js",
             "The %d newest weeks per batch and group, from data/master/weekly/." % WEEKS_ON_SITE,
             "WEEKLY_DATA", site_weeks)

    write_js(ROOT / "js" / "site-data.js", "From data/config/programmes.json and timeline.json.", "SITE_DATA",
             {"programmes": {k: v for k, v in programmes["programmes"].items()},
              "timeline": {k: {f: v[f] for f in ("label", "terms", "alumniFrom") if f in v}
                           for k, v in timeline.items() if not k.startswith("_")}})


def summary(students, weeks):
    print()
    counts = {}
    for s in students.values():
        k = "%s-%s" % (s["batch"], s["group"])
        counts[k] = counts.get(k, 0) + 1
    print("Students:", ", ".join("%s %d" % kv for kv in sorted(counts.items())), "| total", len(students))
    print("Weeks on file:", ", ".join("%s %d" % (k, len(v)) for k, v in sorted(weeks.items())) or "none")
    skipped = [m for m in messages if m[0] in ("SKIPPED", "INBOX")]
    if skipped:
        print("\n%d file(s) need attention - see the SKIPPED / INBOX lines above." % len(skipped))


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    programmes = load("programmes.json")
    timeline = {k: v for k, v in load("timeline.json").items() if not k.startswith("_")}
    overrides = load("overrides.json")
    for section in ("courses", "electives", "students", "sectionFromElective"):
        overrides[section] = {k: v for k, v in overrides.get(section, {}).items() if not k.startswith("_")}
    file_inbox(timeline)
    courses, students, weeks = build_master(overrides)
    build_site(courses, students, weeks, timeline)
    summary(students, weeks)
