#!/usr/bin/env python3
"""
The one command that keeps the site's data current.

    python scripts/update.py              on Khush's machine: everything
    python scripts/update.py --uploads    on GitHub, after a web upload: weekly only

Full run (no flag), every time:

 1. Files anything waiting in "all files/_inbox/". Each file is read to find
    out what it is (weekly schedule, course allocation or student list) and
    which batch, programme group and term it belongs to, then moved to
        all files/batch <year>/<core|bfs|dcp>/term <n>/[weekly/]
    under its original name. A file it cannot place is left in the inbox and
    reported.
 2. Reads every file under "all files/" and "uploads/" again from scratch and
    rebuilds the master data in data/master/:
        students.json   every student: programme, batch, section, courses
        students.csv    the same list as a sheet that opens in Excel
        courses.json    course lists per batch, group and term
        weekly/         every week ever received, per batch and group
 3. Rebuilds the three files the pages load, and re-stamps the pages' links
    to scripts and styles so browsers fetch whatever changed:
        js/site-data.js                 programmes and term timeline
        js/roster-data.js               every student, compact
        weekly-seat/js/weekly-data.js   the two newest weeks per group

Because step 2 always starts from the college's own files, the master data
can never drift from them, and adding a batch, a programme or a term is just
adding files in the right folder.

--uploads is what the GitHub Action runs when weekly schedules are sent from
the upload page. "all files/" is not on GitHub, so this mode touches weekly
schedules only: it files the PDFs waiting in "uploads/_inbox/" under
"uploads/batch .../weekly/", reads them against the course lists already in
data/master/courses.json, adds those weeks to data/master/weekly/ and rebuilds
weekly-seat/js/weekly-data.js. Students and course lists are left exactly as
they are. What happened to each file is written to uploads/last-run.json for
the upload page to show.

A file that fails its checks is skipped with a message and everything else
still builds. Hand-edited settings live in data/config/.

    pip install pymupdf xlrd openpyxl      # once (pymupdf alone for --uploads)
"""
import collections
import datetime as dt
import json
import re
import shutil
import sys
from pathlib import Path

import parsers

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "all files"      # the college's files; never on GitHub
UPLOADS = ROOT / "uploads"       # weekly PDFs sent from the upload page; on GitHub
CONFIG = ROOT / "data" / "config"
MASTER = ROOT / "data" / "master"
WEEKS_ON_SITE = 3
FOLDER = re.compile(r"batch (\d{4})/(core|bfs|dcp)/term (\d)(/|$)")

messages = []


def say(kind, text):
    messages.append((kind, text))
    print("%-8s %s" % (kind, text))


def load(name):
    return json.loads((CONFIG / name).read_text(encoding="utf-8"))


def dump(obj, **kw):
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, **kw)


def write_json(path, obj):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dump(obj, indent=1) + "\n", encoding="utf-8")


def write_js(path, comment, name, obj):
    path.write_text("// Generated by scripts/update.py. Do not hand-edit. %s\nwindow.%s = %s;\n"
                    % (comment, name, dump(obj, separators=(",", ":"))), encoding="utf-8")


def rel(path):
    return path.relative_to(ROOT).as_posix()


def current_term(group_timeline, today):
    term = None
    for t in (group_timeline or {}).get("terms", []):
        if t["start"] <= today or term is None:
            term = t["term"]
    return term


# ------------------------------------------------------------------ 1. inbox

def file_inbox(root, timeline, weekly_only=False):
    """Move each file in <root>/_inbox to <root>/batch ../<group>/term ../[weekly/]."""
    inbox = root / "_inbox"
    if not inbox.is_dir():
        return
    today = dt.date.today().isoformat()
    for path in sorted(p for p in inbox.iterdir() if p.is_file() and not p.name.startswith(".")):
        try:
            info = parsers.describe(path)
        except Exception as e:  # unreadable file: leave it where it is
            say("INBOX", "left in inbox, could not be read: %s (%s)" % (path.name, e))
            continue
        if info.get("_code"):
            info["group"] = programmes["programmes"].get(info["_code"], {}).get("group", info["group"])
        if info["kind"] == "weekly" and not info["batch"] and info["group"] and info["term"]:
            # no "2026-28" anywhere in it: the batch is whichever one has this
            # group in this term during the schedule's week
            try:
                start = parsers.parse_weekly(path)["start"]
                hits = [k.split("-")[0] for k, v in timeline.items()
                        if k.endswith("-" + info["group"]) and current_term(v, start) == info["term"]]
                if len(hits) == 1:
                    info["batch"] = hits[0]
            except Exception:
                pass
        if info["term"] is None and info["batch"] and info["group"]:
            info["term"] = current_term(timeline.get("%s-%s" % (info["batch"], info["group"])), today)
        if info["kind"] == "mess":
            # the mess menu is for everyone: no batch, group or term
            dest = root / "mess"
            dest.mkdir(parents=True, exist_ok=True)
            if (dest / path.name).exists():
                say("NOTE", "replaced the earlier copy of %s" % path.name)
                (dest / path.name).unlink()
            shutil.move(str(path), str(dest / path.name))
            say("FILED", "%s -> mess" % path.name)
            continue
        if weekly_only and info["kind"] != "weekly":
            say("INBOX", "left in inbox, only weekly schedule PDFs can be sent from the upload page: %s" % path.name)
            continue
        if not all(info.get(k) for k in ("kind", "batch", "group", "term")):
            say("INBOX", "left in inbox, could not tell what it is: %s (read as %s)"
                % (path.name, {k: v for k, v in info.items() if not k.startswith("_")}))
            continue
        dest = root / ("batch %s" % info["batch"]) / info["group"] / ("term %d" % info["term"])
        if info["kind"] == "weekly":
            dest = dest / "weekly"
        dest.mkdir(parents=True, exist_ok=True)
        if (dest / path.name).exists():
            say("NOTE", "replaced the earlier copy of %s" % path.name)
            (dest / path.name).unlink()
        shutil.move(str(path), str(dest / path.name))
        say("FILED", "%s -> %s" % (path.name, dest.relative_to(root).as_posix()))


# ----------------------------------------------------------------- 2. reading

def scan(roots):
    """(batch, group, term) -> {'weekly': [paths], 'other': [paths]} across the source folders."""
    found = {}
    for root in roots:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            r = path.relative_to(root).as_posix()
            m = FOLDER.match(r)
            if not path.is_file() or not m:
                continue
            key = (m.group(1), m.group(2), int(m.group(3)))
            bucket = "weekly" if "/weekly/" in r else "other"
            found.setdefault(key, {"weekly": [], "other": []})[bucket].append(path)
    return found


def revise_week(week, gkey):
    """Replace the days listed for this week in data/config/weekly-revisions.json."""
    revision = load("weekly-revisions.json").get(gkey, {}).get(week["start"])
    if not revision:
        return
    dates = [d["date"] for d in week["days"]]
    rooms = {}
    for s in week["sessions"]:
        if s["row"] and s["room"]:
            rooms.setdefault(s["row"], collections.Counter())[s["room"]] += 1
    fresh = []
    for date, rows in revision["days"].items():
        if date not in dates:
            raise ValueError("%s is not in the week of %s" % (date, week["start"]))
        for row, cells in rows.items():
            if row not in week["rows"]:
                raise ValueError("%s: no row %s in this schedule" % (date, row))
            if len(cells) > len(week["slots"]):
                raise ValueError("%s row %s has %d cells, the schedule has %d time slots" % (date, row, len(cells), len(week["slots"])))
            for slot, text in enumerate(cells):
                if not text.strip():
                    continue
                cls = parsers.parse_class(text.strip())
                if not cls:
                    raise ValueError("%s row %s: cannot read '%s'" % (date, row, text))
                cls.update(d=dates.index(date), s=slot, row=row,
                           room=cls["room"] or (rooms[row].most_common(1)[0][0] if row in rooms else None))
                fresh.append(cls)
    revised = {dates.index(date) for date in revision["days"]}
    before = sum(1 for s in week["sessions"] if s["d"] in revised)
    week["sessions"] = [s for s in week["sessions"] if s["d"] not in revised] + fresh
    week["sessions"].sort(key=lambda x: (x["d"], x["s"], x["row"] or "", x["c"], x["sec"] or "", x["grp"] or ""))
    week["revised"] = {"received": revision.get("received"), "days": sorted(revision["days"])}
    say("NOTE", "%s week of %s: %d day(s) replaced from weekly-revisions.json (%d classes in the PDF, %d now)"
        % (gkey, week["start"], len(revised), before, len(fresh)))


def read_week(path, batch, group, term, catalog, electives):
    """One weekly PDF -> the week as stored in data/master/weekly/, or None if it fails its checks."""
    gkey = "%s-%s" % (batch, group)
    try:
        week = parsers.parse_weekly(path)
    except Exception as e:
        say("SKIPPED", "%s: %s" % (rel(path), e))
        return None
    if week["term"] not in (None, term):
        say("NOTE", "%s says Term %s but sits in the term %d folder" % (rel(path), week["term"], term))
    week.update(batch=batch, group=group, term=term, source=rel(path))
    try:
        revise_week(week, gkey)
    except ValueError as e:
        say("SKIPPED", "%s: revision in weekly-revisions.json not applied: %s" % (rel(path), e))
        return None
    lookup ={parsers.norm_code(a): a for a in catalog}
    names = {}
    for s in week["sessions"]:
        abb = lookup.get(parsers.norm_code(s["c"]))
        names[s["c"]] = catalog[abb]["name"] if abb else s["c"]
    unknown = sorted(c for c, n in names.items() if c == n)
    if unknown:
        week["warnings"].append("no course name for %s (add to data/config/overrides.json)" % ", ".join(unknown))
    week["courses"] = names
    week["electives"] = electives
    for w in week.pop("warnings"):
        say("NOTE", "%s: %s" % (gkey, w))
    say("WEEK", "%s term %d, %s to %s: %d classes, %d other entries  [%s layout]"
        % (gkey, term, week["start"], week["end"], len(week["sessions"]), len(week["specials"]), week["mode"]))
    return week


def build_master(overrides):
    found = scan([SOURCE, UPLOADS])
    courses, students, weeks = {}, {}, {}
    latest_term = {}
    for (batch, group, term) in sorted(found):
        latest_term[(batch, group)] = max(term, latest_term.get((batch, group), 0))

    for (batch, group, term), files in sorted(found.items()):
        key = "%s-%s-%d" % (batch, group, term)
        gkey = "%s-%s" % (batch, group)
        catalog = {}
        lists = []
        for path in files["other"]:
            try:
                kind = parsers.describe(path)["kind"]
                if kind == "courses":
                    parsed, warns = parsers.parse_courses(path)
                    catalog.update(parsed)
                    for w in warns:
                        say("NOTE", w)
                elif kind == "students":
                    lists.append(path)
                else:
                    say("SKIPPED", "%s: not a course or student list" % rel(path))
            except Exception as e:
                say("SKIPPED", "%s: %s" % (rel(path), e))
        for abb, name in overrides["courses"].get(key, {}).items():
            catalog.setdefault(abb, {})["name"] = name
        courses[key] = catalog

        # the newest term's lists describe where each student is now
        if term == latest_term[(batch, group)]:
            for path in lists:
                try:
                    parsed, notes = parsers.parse_students(path, catalog)
                    for n in notes:
                        say("NOTE", n)
                except Exception as e:
                    say("SKIPPED", "%s: %s" % (rel(path), e))
                    continue
                for roll, entry in parsed.items():
                    if roll in students and students[roll]["group"] != group:
                        say("NOTE", "roll %s is in both the %s and %s lists" % (roll, students[roll]["group"], group))
                    code = roll[2:6] if re.fullmatch(r"\d{9}", roll) else ("FPM" if "FPM" in roll else None)
                    entry.update(batch=batch, group=group, term=term, programme=code)
                    if entry.get("electives") and students.get(roll, {}).get("electives"):
                        both = sorted(set(students[roll]["electives"]) | set(entry["electives"]))
                        if len(both) > 1:
                            say("NOTE", "roll %s is on more than one elective list (%s); shown all of them" % (roll, ", ".join(both)))
                        entry["electives"] = both
                    students[roll] = {**students.get(roll, {}), **entry}

        for path in files["weekly"]:
            week = read_week(path, batch, group, term, catalog, overrides["electives"].get(key, []))
            if week:
                weeks.setdefault(gkey, {})[week["start"]] = week

    for roll, entry in overrides["students"].items():
        students[roll] = {**students.get(roll, {}), **entry}

    # a batch with only one section's list supplied: everyone else is in the other
    defaulted = {}
    for s in students.values():
        key = "%s-%s-%s" % (s["batch"], s["group"], s.get("term"))
        if key in overrides["defaultSection"] and not s.get("section"):
            s["section"] = overrides["defaultSection"][key]
            s["sectionByDefault"] = True
            defaulted[key] = defaulted.get(key, 0) + 1
    for key, n in sorted(defaulted.items()):
        say("NOTE", "%s: %d students not on a section list placed in Section %s (defaultSection in overrides.json)"
            % (key, n, overrides["defaultSection"][key]))

    # stop-gap sections: only for students whose lists give no section
    assumed = {}
    for s in students.values():
        rule = overrides["sectionFromElective"].get("%s-%s-%s" % (s["batch"], s["group"], s.get("term")))
        chosen = [e for e in s.get("electives", []) if rule and e in rule]
        if rule and not s.get("section") and len(chosen) == 1:
            s["section"] = rule[chosen[0]]
            s["sectionAssumed"] = True
            key = "%s-%s" % (s["batch"], s["group"])
            assumed[key] = assumed.get(key, 0) + 1
    for key, n in sorted(assumed.items()):
        say("NOTE", "%s: %d students given a section from their elective (stop-gap in overrides.json)" % (key, n))
    return courses, students, weeks


# ------------------------------------------------------------------- 3. site

MESS_DAYS_ON_SITE = 45


def build_mess(roots):
    """The mess menu: every menu PDF in <root>/mess laid over data/master/mess.json
    (a later file wins for a date both have), then js/mess-data.js for the pages."""
    master = MASTER / "mess.json"
    mess = json.loads(master.read_text(encoding="utf-8")) if master.exists() else {"days": {}, "timings": {}, "note": ""}
    files = sorted((p for root in roots for p in (root / "mess").glob("*.pdf")), key=lambda p: (p.stat().st_mtime, p.name))
    for path in files:
        try:
            menu = parsers.parse_mess(path)
        except Exception as e:
            say("SKIPPED", "%s: %s" % (rel(path), e))
            continue
        mess["days"].update(menu["days"])
        mess["timings"] = menu["timings"] or mess["timings"]
        mess["note"] = menu["note"] or mess["note"]
        for w in menu["warnings"]:
            say("NOTE", "mess menu, %s: %s" % (path.name, w))
        say("MESS", "%s: %s to %s, %d days" % (path.name, min(menu["days"]), max(menu["days"]), len(menu["days"])))
    mess["days"] = dict(sorted(mess["days"].items()))
    if not mess["days"]:
        return
    write_json(master, mess)
    recent = dict(list(mess["days"].items())[-MESS_DAYS_ON_SITE:])
    write_js(ROOT / "js" / "mess-data.js", "The mess menu, newest %d days, from data/master/mess.json." % MESS_DAYS_ON_SITE,
             "MESS_DATA", {"days": recent, "timings": mess["timings"], "note": mess["note"]})


def bundle_weekly():
    """weekly-seat/js/weekly-data.js from whatever is in data/master/weekly/."""
    site = {}
    for folder in sorted((MASTER / "weekly").glob("*")):
        newest = sorted(folder.glob("*.json"))[-WEEKS_ON_SITE:]
        site[folder.name] = [
            {k: w[k] for k in ("term", "weekNumber", "start", "end", "mode", "rowLabel", "rows",
                               "slots", "days", "sessions", "specials", "courses", "electives")}
            for w in (json.loads(p.read_text(encoding="utf-8")) for p in newest)]
    write_js(ROOT / "weekly-seat" / "js" / "weekly-data.js",
             "The %d newest weeks per batch and group, from data/master/weekly/." % WEEKS_ON_SITE,
             "WEEKLY_DATA", site)
    return site


def write_students_csv(students):
    """data/master/students.csv: the same student list as students.json, as a
    sheet that opens in Excel, sorted by batch, group, section and roll."""
    import csv
    names = programmes["programmes"]
    rows = sorted(students.items(), key=lambda kv: (kv[1]["batch"], kv[1]["group"], kv[1].get("section", ""), kv[0]))
    with (MASTER / "students.csv").open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["Roll No", "Name", "Batch", "Programme", "Group", "Term", "Section", "Track",
                    "Major", "Minor", "Electives", "Courses (course-section)"])
        for roll, s in rows:
            w.writerow([roll, s["name"], "%d-%s" % (int(s["batch"]) - 2, s["batch"][2:]),
                        names.get(s.get("programme") or "", {}).get("name", ""), s["group"], s.get("term", ""),
                        s.get("section", "") + (" (from elective)" if s.get("sectionAssumed") else "")
                        + (" (not on the other section's list)" if s.get("sectionByDefault") else ""),
                        s.get("track", ""), s.get("major", ""), s.get("minor", ""),
                        ", ".join(s.get("electives", [])),
                        ", ".join("%s-%s" % kv for kv in sorted(s.get("courses", {}).items()))])


def build_site(courses, students, weeks, timeline, overrides):
    shutil.rmtree(MASTER, ignore_errors=True)
    write_json(MASTER / "students.json", students)
    write_json(MASTER / "courses.json", courses)
    write_students_csv(students)
    for gkey, by_start in weeks.items():
        for start, week in by_start.items():
            write_json(MASTER / "weekly" / gkey / ("%s.json" % start), week)

    roster = {}
    short = {"name": "n", "section": "s", "major": "mj", "minor": "mn", "track": "t",
             "courses": "c", "electives": "e", "programme": "p", "alumni": "al"}
    for roll, s in students.items():
        entry = {"g": "%s-%s" % (s["batch"], s["group"])}
        for long, key in short.items():
            if s.get(long):
                entry[key] = s[long]
        roster[roll] = entry
    write_js(ROOT / "js" / "roster-data.js", "Every student in data/master/students.json.", "ROSTER_DATA", roster)
    bundle_weekly()
    write_js(ROOT / "js" / "site-data.js", "From data/config/programmes.json and timeline.json.", "SITE_DATA",
             {"programmes": programmes["programmes"],
              # course lists, electives and alternative spellings: used by Exam Seat to
              # pick a student's own paper where two papers share a hall
              "courses": {k: {abb: c["name"] for abb, c in v.items()} for k, v in courses.items()},
              "electives": overrides["electives"],
              "examAliases": overrides["examAliases"],
              "timeline": {k: {f: v[f] for f in ("label", "terms", "alumniFrom") if f in v} for k, v in timeline.items()}})


def summary(students, weeks):
    print()
    counts = {}
    for s in students.values():
        k = "%s-%s" % (s["batch"], s["group"])
        counts[k] = counts.get(k, 0) + 1
    print("Students:", ", ".join("%s %d" % kv for kv in sorted(counts.items())), "| total", len(students))
    print("Weeks on file:", ", ".join("%s %d" % (k, len(v)) for k, v in sorted(weeks.items())) or "none")
    skipped = [m for m in messages if m[0] in ("SKIPPED", "INBOX")]
    if skipped:
        print("\n%d file(s) need attention - see the SKIPPED / INBOX lines above." % len(skipped))


PAGES = ["index.html", "weekly-seat/index.html", "exam-seat/index.html", "upload/index.html"]


def stamp_pages():
    """Give every local script and stylesheet link a ?v=<fingerprint of the file>.
    Browsers keep these files for a while; a link that changes whenever the
    file does makes them fetch the new one straight away, so nobody is left
    looking at last week's data or an old button."""
    import hashlib
    for name in PAGES:
        page = ROOT / name
        if not page.exists():
            continue
        html = page.read_text(encoding="utf-8")

        def stamp(m):
            target = (page.parent / m.group(2)).resolve()
            if not target.is_file():
                return m.group(0)
            digest = hashlib.md5(target.read_bytes().replace(b"\r\n", b"\n")).hexdigest()[:8]
            return '%s="%s?v=%s"' % (m.group(1), m.group(2), digest)

        stamped = re.sub(r'(src|href)="(?!https?:|//)([^"?#]+\.(?:js|css))(?:\?v=[0-9a-f]+)?"', stamp, html)
        if stamped != html:
            page.write_text(stamped, encoding="utf-8", newline="\n")


# ------------------------------------------------- the upload page's weekly run

def run_uploads(timeline, overrides):
    """Weekly schedules only, against the master data already in the repo."""
    courses = json.loads((MASTER / "courses.json").read_text(encoding="utf-8"))
    file_inbox(UPLOADS, timeline, weekly_only=True)
    loaded = []
    for (batch, group, term), files in sorted(scan([UPLOADS]).items()):
        key = "%s-%s-%d" % (batch, group, term)
        if key not in courses:
            say("NOTE", "%s: no course list on file for this term yet, so classes show as abbreviations" % key)
        for path in files["weekly"]:
            week = read_week(path, batch, group, term, courses.get(key, {}), overrides["electives"].get(key, []))
            if week:
                gkey = "%s-%s" % (batch, group)
                write_json(MASTER / "weekly" / gkey / ("%s.json" % week["start"]), week)
                loaded.append({"group": gkey, "term": term, "start": week["start"], "end": week["end"],
                               "classes": len(week["sessions"]), "file": path.name})
    bundle_weekly()
    build_mess([UPLOADS])
    report = {
        "ranAt": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "weeks": loaded,
        "messages": [{"kind": k, "text": t} for k, t in messages if k != "WEEK"],
    }
    write_json(UPLOADS / "last-run.json", report)
    stamp_pages()
    print("\n%d week(s) on file from uploads." % len(loaded))


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    programmes = load("programmes.json")
    timeline = {k: v for k, v in load("timeline.json").items() if not k.startswith("_")}
    overrides = load("overrides.json")
    for section in ("courses", "electives", "students", "sectionFromElective", "defaultSection", "examAliases"):
        overrides[section] = {k: v for k, v in overrides.get(section, {}).items() if not k.startswith("_")}
    if "--uploads" in sys.argv[1:]:
        run_uploads(timeline, overrides)
    else:
        file_inbox(SOURCE, timeline)
        courses, students, weeks = build_master(overrides)
        build_site(courses, students, weeks, timeline, overrides)
        build_mess([SOURCE, UPLOADS])
        stamp_pages()
        summary(students, weeks)
